#!/bin/bash
function mig_url_change() {
  read -p 'Enter old url → ' old_url_input
  read -p 'Enter new url → ' new_url_input
  temp_old_url=$(echo $old_url_input | sed -rn 's|(http)?(s)?(://)?(www.)?(.*)|\5|p')
  temp_new_url=$(echo $new_url_input | sed -rn 's|(http)?(s)?(://)?(www.)?(.*)|\5|p')
  new_url=$(echo "://$temp_new_url")
  old_url=$(echo "://$temp_old_url")
  www_old_url=$(echo "://www.$temp_old_url")
  www_new_url=$(echo "://www.$temp_new_url")
  echo "replacing $old_url with $new_url"
  # echo wpurl -n http"$new_url"
  wpurl -n http"$new_url" 1>/dev/null
  # echo "wp search-replace $old_url $new_url"
  # echo "wp search-replace $www_old_url $www_new_url"
  wp search-replace "$old_url" "$new_url" 1>/dev/null
  wp search-replace "$www_old_url" "$www_new_url" 1>/dev/null
  migssl -off 1>/dev/null
  wpurl 
}
mig_url_change
