#!/bin/bash
function sqlformatting() {
    echo -e "Prefix:#$prefix\nHome:#$home\nSiteURL:#$siteurl\nUpload Path:#$upload_path\nTemplate:#$template\nStylesheet:#$stylesheet\nExported#$exported\nActive Plugins:\n" | column -t -s '#'
}
function searchdumps() {
    prefixlist=($(grep -oP 'CREATE TABLE.+[^\w]\K\w+_(?=options)' $dbfile))
    if [[ -n "${prefixlist[0]}" ]]; then
        for prefix in "$prefixlist"; do
            siteurl=$(grep -m1 -oP "INSERT INTO.+($prefix)(options).+siteurl(\'|\")[\,\s]+(\'|\")\Khttp(s)?\:\/\/[\w\.\/\-]+(?=\'|\")" $dbfile)
            if [[ -n "$siteurl" ]]; then
                i=0
                home=$(grep -m1 -oP "INSERT INTO.+($prefix)(options).+home(\'|\")[\,\s]+(\'|\")\Khttp(s)?\:\/\/[\w\.\/\-]+(?=\'|\")" $dbfile)
                upload_path=$(grep -m1 -oP "INSERT INTO.+($prefix)(options).+upload_path(\'|\")[\,\s]+\K(\'|\")[^\'\"]*('|\")" $dbfile)
                template=$(grep -m1 -oP "INSERT INTO.+($prefix)(options).+template(\'|\")[\,\s]+(\'|\")\K[^\'\"]*(?=\'|\")" $dbfile)
                stylesheet=$(grep -m1 -oP "INSERT INTO.+($prefix)(options).+stylesheet(\'|\")[\,\s]+(\'|\")\K[^\'\"]*(?=\'|\")" $dbfile)
                plugins_unformatted=$(grep -oP "INSERT INTO.+($prefix)(options).+\Kactive_plugins(\'|\")[\,\s]+(\'|\")a\:\d+\:\{\K[^\}]+" $dbfile)
                plugins=($(echo "$plugins_unformatted" | grep -oP "i\:\d+\;s\:\d+\:.(\'|\")\K[\w\.\-]+"))
                exported=$(tail $dbfile | sed -rn 's/\-\- Dump completed on\s+//p')

                echo -e "\n==> $dbfile <=="
                sqlformatting
                for plugin in ${plugins[@]}; do
                    echo -e "\t\t $plugin"
                done
            else
                echo "Could not find wp prefix in $dbfile"
            fi
        done
    else
        echo "Could not find wp prefix in $dbfile"
    fi
}
function wpcheck() {
    if [[ -s "$dbfile" ]]; then
        iswp=$(grep -ois -m 1 'wordpress' "$dbfile" | head -n 1)
        if [[ -z "$iswp" ]]; then
            echo -e "\n$dbfile does not appear to be a WordPress database dump. More likely Pat made a mistake when making this script."
        else
            searchdumps "$dbfile"
        fi
    elif [[ -f "$dbfile" ]]; then
        echo -e "\n$dbfile is empty."
    else 
        echo -e "\n$1 does not exist in this directory."
    fi
}
function main() {
    if [[ -n "$1" ]]; then
        if [[ -f "$1" ]]; then
            for dbfile in "$@"; do
                wpcheck "$dbfile"
            done
        else
            echo -e "\n$1 does not exist in this directory."
        fi
    else
        sqlfiles=($(ls -1 *.sql 2>/dev/null))
        if [[ "${#sqlfiles[@]}" -gt '0' ]]; then
            for dbfile in "${sqlfiles[@]}"; do
                if [[ -f "$dbfile" ]]; then
                    wpcheck "$dbfile"
                fi
            done
        else
            echo -e '\nNo .sql files in this directory. Please provide 1 or more files (searchdumps $file1 $file2 etc...) or run in a directory that holds mysqldump files ending in .sql'
        fi
    fi
}
main $@
